# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainrecon < Formula
  desc "Find the next supply chain attack before the attacker does."
  homepage "https://github.com/chainrecon/chainrecon"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.3.0/chainrecon_0.3.0_darwin_amd64.tar.gz"
      sha256 "eeffe08fb94171a1215187be047a4b757239bd207bcd1580c75dacacc19b2f01"

      define_method(:install) do
        bin.install "chainrecon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.3.0/chainrecon_0.3.0_darwin_arm64.tar.gz"
      sha256 "b46ac16cf61ee96bf34fc2f0862bb8edb6ab22dadf2a5b4f17459ba47e90e914"

      define_method(:install) do
        bin.install "chainrecon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.3.0/chainrecon_0.3.0_linux_amd64.tar.gz"
      sha256 "e82d98d977a6981e712a572a32fa4b81a8e07e691183f0676dd551cf5ec11ad6"
      define_method(:install) do
        bin.install "chainrecon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.3.0/chainrecon_0.3.0_linux_arm64.tar.gz"
      sha256 "3384bd162d0a860a761fbb6d83a0964d90c4decd041eafdfa7d412b5a9be1900"
      define_method(:install) do
        bin.install "chainrecon"
      end
    end
  end

  test do
    system "#{bin}/chainrecon", "version"
  end
end
