# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainrecon < Formula
  desc "Find the next supply chain attack before the attacker does."
  homepage "https://github.com/chainrecon/chainrecon"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.2.0/chainrecon_0.2.0_darwin_amd64.tar.gz"
      sha256 "73b2f7cc723b6ba8a85bffc2e020fc736413532c528a6a28b57976181fac348c"

      define_method(:install) do
        bin.install "chainrecon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.2.0/chainrecon_0.2.0_darwin_arm64.tar.gz"
      sha256 "14d366cffdbb345a0bbd84c88ddb7a2d2e23bd1d246c891baed6de51e60d1e37"

      define_method(:install) do
        bin.install "chainrecon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.2.0/chainrecon_0.2.0_linux_amd64.tar.gz"
      sha256 "25d02887c8ce7d777d9b543c5a599b9b65f50b8f46ebd0ae1273aff00f1bd901"
      define_method(:install) do
        bin.install "chainrecon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainrecon/chainrecon/releases/download/v0.2.0/chainrecon_0.2.0_linux_arm64.tar.gz"
      sha256 "4d747b3ea743fe810541fcd8c877dcd0415d1aab74205215f363d4dbef0c5813"
      define_method(:install) do
        bin.install "chainrecon"
      end
    end
  end

  test do
    system "#{bin}/chainrecon", "version"
  end
end
